
---
title: "occCite Vignette"
author: "Hannah Owens and Cory Merow"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{An overview of making rangeModelMetadata objects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
```

# Introduction 

```{r}
library(occCite);
library(ape);

##Simple search
#Query databases for names
myOccCiteObject <- studyTaxonList(x = "Protea cynaroides");

#Query GBIF for occurrence data
login <- GBIFLoginManager(user = "wallacetester",
                          email = "cmerow@yahoo.com",
                          pwd = "wallacetester");
myOccCiteObject <- occQuery(x = myOccCiteObject, GBIFLogin = login, GBIFDownloadDirectory = "~/Desktop");

#Get citations
myOccCitations <- occCitation(myOccCiteObject);

##With a tree
#Get tree
# the next one should work now CM(12/6)
#tree <- read.nexus("~/Dropbox/occCite/TestData/Fish_12Tax_time_calibrated.tre");
# try
tree <- read.nexus(system.file("extdata/Fish_12Tax_time_calibrated.tre",package='occCite'))
#Query databases for names
myOccCiteObject <- studyTaxonList(x = tree, datasources = "NCBI");

#Query GBIF for occurrence data
login <- GBIFLoginManager(user = "wallacetester",
                          email = "cmerow@yahoo.com",
                          pwd = "wallacetester");
myOccCiteObject <- occQuery(x = myOccCiteObject, GBIFLogin = login, GBIFDownloadDirectory = "~/Desktop");

#Get citations
myOccCitations <- occCitation(myOccCiteObject);

```

