# Workflow originally based on r-lib/actions examples
# Updated with guidance from ChatGPT (OpenAI) to support additional repositories (e.g., R-universe)
# and fix CI failures with optional packages like waffle.

on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Teach pak about the R-universe repo BEFORE dependency resolution
      - name: Add R-universe repo for pak 
        run: |
          Rscript -e 'install.packages("pak", repos = "https://cloud.r-project.org")'
          Rscript -e 'pak::repo_add("hrbrmstr", "https://hrbrmstr.r-universe.dev"); pak::repo_get()'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: any::covr, any::xml2
          needs: coverage
          cache-version: 1

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || '1c6632bd-26a7-4d8a-a603-02cb346ccd34' }}
          files: ./cobertura.xml
          plugins: noop
          disable_search: true
          token: ${{ '1c6632bd-26a7-4d8a-a603-02cb346ccd34' }}

      - name: Show testthat output
        if: always()
        run: |
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
